Revert `const`-ness of `FmtRenderer::new()`
It turns out that the ability to mark such a function as `const` was
only just stabilized in rust 1.61 and earlier versions reported an error
regarding the use of an unsupported/unstable feature:

```
error[E0658]: trait bounds other than `Sized` on const fn parameters are
unstable
   --> src/fmt.rs:201:6
    |
201 | impl<F: Fn(&mut fmt::Formatter) -> fmt::Result> FmtRenderer<F> {
    |      ^
202 |     pub const fn new(formatter: F) -> Self {
    |     -------------------------------------- function declared as
    |                                            const here
    |
    = note: see issue #57563
    = <https://github.com/rust-lang/rust/issues/57563> for more
    = information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate
    = attributes to enable
```