Use a hack to fake modern rust for a test
The existing code didn't compile under 1.50 (see below) due to
unsupported drain syntax while iterating over an array by value.

We use an immense hack to make it look like we are using modern rust
syntax but actually iterate over a reference to the array so that the
test passes under older rustc versions.

```
---- src/fmt.rs - fmt::SizeFormatter (line 165) stdout ----
error[E0308]: mismatched types
  --> src/fmt.rs:177:38
   |
15 |     let formatted = formatter.format(raw_size);
   |                                      ^^^^^^^^
   |                                      |
   |                                      expected `i64`, found
   |                                      `&{integer}`
   |                                      help: consider dereferencing
   |                                      the borrow: `*raw_size`

error: aborting due to previous error
```